name = "synchrove-hub-backend"
main = "src/index.js"
compatibility_date = "2024-05-16"

[[d1_databases]]
binding = "DB"
database_name = "synchrove"
database_id = "082285f0-c2ff-4e6f-9eaa-ef11bc434924"
